product = {
  "data": {
    "country": "IN",
    "domain": "www.amazon.in",
    "products": [
      {
        "asin": "B0CHX2F5QT",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b972,999",
        "product_num_offers": 0,
        "product_num_ratings": 720,
        "product_original_price": "\u20b979,900",
        "product_photo": "https://m.media-amazon.com/images/I/71d7rfSl0wL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b972,999",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 15 (128 GB) - Blue",
        "product_url": "https://www.amazon.in/dp/B0CHX2F5QT",
        "sales_volume": None
      },
      {
        "asin": "B0CHXCR9CX",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b980,990",
        "product_num_offers": 0,
        "product_num_ratings": 372,
        "product_original_price": "\u20b989,900",
        "product_photo": "https://m.media-amazon.com/images/I/71zFRCcMS2L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b980,990",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 15 Plus (128 GB) - Black",
        "product_url": "https://www.amazon.in/dp/B0CHXCR9CX",
        "sales_volume": None
      },
      {
        "asin": "B0CHX5J2ND",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b91,37,990",
        "product_num_offers": 0,
        "product_num_ratings": 146,
        "product_original_price": "\u20b91,44,900",
        "product_photo": "https://m.media-amazon.com/images/I/81CgtwSII3L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b91,37,990",
        "product_star_rating": "4.1",
        "product_title": "Apple iPhone 15 Pro (256 GB) - Natural Titanium",
        "product_url": "https://www.amazon.in/dp/B0CHX5J2ND",
        "sales_volume": None
      },
      {
        "asin": "B0CHX6N27Y",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b980,990",
        "product_num_offers": 0,
        "product_num_ratings": 720,
        "product_original_price": "\u20b989,900",
        "product_photo": "https://m.media-amazon.com/images/I/71d7rfSl0wL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b980,990",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 15 (256 GB) - Blue",
        "product_url": "https://www.amazon.in/dp/B0CHX6N27Y",
        "sales_volume": None
      },
      {
        "asin": "B0CHX1K2ZC",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Mon, 26 Feb Or fastest delivery Sat, 24 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b91,48,900",
        "product_num_offers": 0,
        "product_num_ratings": 86,
        "product_original_price": "\u20b91,59,900",
        "product_photo": "https://m.media-amazon.com/images/I/81fxjeu8fdL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b91,48,900",
        "product_star_rating": "4.6",
        "product_title": "Apple iPhone 15 Pro Max (256 GB) - Blue Titanium",
        "product_url": "https://www.amazon.in/dp/B0CHX1K2ZC",
        "sales_volume": None
      },
      {
        "asin": "B09G9HDN4Q",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b961,900",
        "product_num_offers": 0,
        "product_num_ratings": 25744,
        "product_original_price": "\u20b979,900",
        "product_photo": "https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b961,900",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 13 (256GB) - (Product) RED",
        "product_url": "https://www.amazon.in/dp/B09G9HDN4Q",
        "sales_volume": None
      },
      {
        "asin": "B0CHX6NQMD",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b971,490",
        "product_num_offers": 0,
        "product_num_ratings": 720,
        "product_original_price": "\u20b979,900",
        "product_photo": "https://m.media-amazon.com/images/I/71nvkHnPpZL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b971,490",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 15 (128 GB) - Green",
        "product_url": "https://www.amazon.in/dp/B0CHX6NQMD",
        "sales_volume": None
      },
      {
        "asin": "B0CHX1W1XY",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b971,490",
        "product_num_offers": 0,
        "product_num_ratings": 720,
        "product_original_price": "\u20b979,900",
        "product_photo": "https://m.media-amazon.com/images/I/71657TiFeHL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b971,490",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 15 (128 GB) - Black",
        "product_url": "https://www.amazon.in/dp/B0CHX1W1XY",
        "sales_volume": None
      },
      {
        "asin": "B0CHX6X2WW",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b980,990",
        "product_num_offers": 0,
        "product_num_ratings": 372,
        "product_original_price": "\u20b989,900",
        "product_photo": "https://m.media-amazon.com/images/I/71PjpS59XLL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b980,990",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 15 Plus (128 GB) - Blue",
        "product_url": "https://www.amazon.in/dp/B0CHX6X2WW",
        "sales_volume": None
      },
      {
        "asin": "B0CHX3TW6X",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b971,490",
        "product_num_offers": 0,
        "product_num_ratings": 720,
        "product_original_price": "\u20b979,900",
        "product_photo": "https://m.media-amazon.com/images/I/71v2jVh6nIL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b971,490",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 15 (128 GB) - Pink",
        "product_url": "https://www.amazon.in/dp/B0CHX3TW6X",
        "sales_volume": None
      },
      {
        "asin": "B09G9D8KRQ",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b951,790",
        "product_num_offers": 0,
        "product_num_ratings": 25744,
        "product_original_price": "\u20b959,900",
        "product_photo": "https://m.media-amazon.com/images/I/71GLMJ7TQiL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b951,790",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 13 (128GB) - Starlight",
        "product_url": "https://www.amazon.in/dp/B09G9D8KRQ",
        "sales_volume": None
      },
      {
        "asin": "B0CHX4CRND",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b984,900",
        "product_num_offers": 0,
        "product_num_ratings": 720,
        "product_original_price": "\u20b989,900",
        "product_photo": "https://m.media-amazon.com/images/I/71v2jVh6nIL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b984,900",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 15 (256 GB) - Pink",
        "product_url": "https://www.amazon.in/dp/B0CHX4CRND",
        "sales_volume": None
      },
      {
        "asin": "B09G9HD6PD",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Mon, 26 Feb Or fastest delivery Sat, 24 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b951,790",
        "product_num_offers": 0,
        "product_num_ratings": 25744,
        "product_original_price": "\u20b959,900",
        "product_photo": "https://m.media-amazon.com/images/I/61VuVU94RnL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b951,790",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 13 (128GB) - Midnight",
        "product_url": "https://www.amazon.in/dp/B09G9HD6PD",
        "sales_volume": None
      },
      {
        "asin": "B09G9BL5CP",
        "climate_pledge_friendly": False,
        "currency": "INR",
        "delivery": "FREE delivery Sat, 24 Feb Or fastest delivery Tomorrow, 23 Feb",
        "is_amazon_choice": False,
        "is_best_seller": False,
        "is_prime": True,
        "product_minimum_offer_price": "\u20b951,790",
        "product_num_offers": 0,
        "product_num_ratings": 25744,
        "product_original_price": "\u20b959,900",
        "product_photo": "https://m.media-amazon.com/images/I/71xb2xkN5qL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_price": "\u20b951,790",
        "product_star_rating": "4.5",
        "product_title": "Apple iPhone 13 (128GB) - Blue",
        "product_url": "https://www.amazon.in/dp/B09G9BL5CP",
        "sales_volume": None
      }
    ],
    "total_products": 957
  },
  "request_id": "1598c3a2-8782-404d-8aa3-672c852135fa",
  "status": "OK"
}


print(product["data"]["products"][1])